
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: reposicao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  reposicao-service:
    image: vitor/reposicao-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reposicao-service
    ports:
      - "8085:8085"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: reposicao
      DB_URL_PARAM: ?ssl=false
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
